"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
scan_timeout = 50
command_timeout = 1000
follow_symlinks = true

format = '$character$directory'
# right_format = '$terraform$c$zig$odin$golang$rust$ruby$python${custom.hugo}([\[](#49443C)$git_state$git_status$git_metrics$git_branch$git_commit[\]](#49443C))$battery'

right_format = """
$singularity\
$kubernetes\
$vcsh\
$fossil_branch\
$git_branch\
$git_commit\
$git_state\
$git_status\
$hg_branch\
$pijul_channel\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$buf\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$crystal\
$custom\
$status\
$os\
$battery\
$time"""

palette = "catppuccin_mocha"

[character]
success_symbol = "[[󰄛](green) ➜](peach)"
error_symbol = "[[󰄛](red) ➜](peach)"

[directory]
truncation_length = 8
read_only = " 󰌾"
truncation_symbol = '…/'
style = 'bold lavender'

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
rebase = '[rebasing](bold maroon)'
merge = '[merging](bold yellow)'
revert = '[reverting](bold blue)'
cherry_pick = '[picking](bold red)'
bisect = '[bisecting](bold red)'
am = '[applying](bold green)'
am_or_rebase = '[applying/rebasing](bold yellow)'

[git_status]
# format = '($all_status$ahead_behind )'
format = "([⎪$ahead_behind$staged$modified$untracked$renamed$deleted$conflicted$stashed⎥]($style))"
style = '8'
up_to_date = '[](teal)'
untracked = '[.](surface1)'
conflicted = '[#](maroon)'
ahead = '[⇡│[${count}](bold white)│](green)'
behind = '[⇣│[${count}](bold white)│](peach)'
diverged = '[⇕ ▴┤[${ahead_count}](regular white)│▿┤[${behind_count}](regular white)│](red)'
stashed = '[^](peach)'
modified = '[*](sky)'
staged = '[+┤[$count](bold white)│](blue)'
renamed = '[»](yellow)'
deleted = '[x](pink)'

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style)'
symbol = ''
style = 'bold mauve'
truncation_length = 11
truncation_symbol = '⋯'
ignore_branches = []

[git_commit]
format = ' [$hash$tag]($style)'
style = '8'
only_detached = false
commit_hash_length = 6
tag_symbol = ''

[git_metrics]
disabled = false
added_style = 'surface0'
deleted_style = 'maroon'
format = '([+$added]($added_style))([-$deleted]($deleted_style)) '

[c]
format = '[$symbol($version )]($style)'
style = '#717C7C'
symbol = ' '

[lua]
format = " [lua](italic) [${symbol}${version}]($style)"
version_format = "${raw}"
symbol = "⨀ "
style = "bold bright-yellow"

[nodejs]
format = " [node](italic) [◫ ($version)](bold bright-green)"
version_format = "${raw}"
detect_files = ["package-lock.json", "yarn.lock"]
detect_folders = ["node_modules"]
detect_extensions = []

[golang]
format = '[$symbol($version )]($style)'
style = 'sky'
symbol = ' '

[odin]
format = '[$symbol($version )]($style)'
style = 'sapphire'
symbol = 'Ø '

[python]
format = '[$symbol($version )]($style)'
style = 'green'
symbol = ' '

[ruby]
format = '[$symbol($version )]($style)'
style = 'red'
symbol = ' '

[rust]
format = '[$symbol($version )]($style)'
style = 'peach'
symbol = ' '

[terraform]
format = '[$symbol$workspace]($style)'
style = 'lavender'
symbol = ' '

[zig]
format = '[$symbol($version )]($style)'
style = 'yellow'
symbol = ' '

[docker_context]
symbol = " "
format = " docker [$symbol$context]($style)"

[custom.hugo]
format = '[$symbol($output )]($style)'
style = 'pink'
symbol = ' '
command = "hugo version | cut -d ' ' -f2 | cut -d '+' -f1"
when = "test -f $(git rev-parse --show-toplevel)/config/_default/config.*"
require_repo = true


[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
